[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_ENV_VALIDATION = "true"
  NETLIFY_BUILD = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Headers for security and PWA support
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "notifications=self"

# Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# APK download headers
[[headers]]
  for = "/downloads/*"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"

[dev]
  command = "npm run dev"
  port = 3000

# Production environment variables
[context.production.environment]
  NEXTAUTH_URL = "https://limitbreakers-app.netlify.app"
  MONGODB_URI = "mongodb+srv://limitbreakers:LimitBreakers123@cluster0.mongodb.net/limitbreakers?retryWrites=true&w=majority"
  NEXTAUTH_SECRET = "yctmXGAO+a6WEW/YGEaoixz9frh4f4DuzaxBG7iHz/E="

# Example: Redirect API routes to Netlify Functions (if needed)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
