[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Headers for security and APK files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specific headers for APK files
[[headers]]
  for = "/downloads/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=31536000"

# Headers for APK files at root
[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=31536000"

# Headers for test files
[[headers]]
  for = "/*.txt"
  [headers.values]
    Content-Type = "text/plain"

[dev]
  command = "npm run dev"
  port = 3000

# Production environment variables
[context.production.environment]
  NEXTAUTH_URL = "https://limibreakers.netlify.app"
  MONGODB_URI = "mongodb://thisisnithin1122:Galaxcy1122%40@ac-bpxktke-shard-00-00.5pm5vmp.mongodb.net:27017,ac-bpxktke-shard-00-01.5pm5vmp.mongodb.net:27017,ac-bpxktke-shard-00-02.5pm5vmp.mongodb.net:27017/?ssl=true&authSource=admin&replicaSet=atlas-wit1qd-shard-0&retryWrites=true&w=majority"
  NEXTAUTH_SECRET = "yctmXGAO+a6WEW/YGEaoixz9frh4f4DuzaxBG7iHz/E="
