#!/bin/bash

# MongoDB Atlas Setup Guide for Limit Breakers
echo "🚀 Setting up MongoDB Atlas for Limit Breakers..."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. 📝 Create MongoDB Atlas Account:"
echo "   - Go to: https://www.mongodb.com/atlas"
echo "   - Click 'Try Free' and create an account"
echo ""
echo "2. 🏗️ Create a New Cluster:"
echo "   - Choose 'Build a Database'"
echo "   - Select 'M0 Sandbox' (Free)"
echo "   - Choose AWS as provider"
echo "   - Select region closest to you"
echo "   - Name your cluster (e.g., 'LimitBreakers')"
echo ""
echo "3. 🔐 Create Database User:"
echo "   - Username: limitbreakers-user"
echo "   - Generate a secure password (save it!)"
echo "   - Set 'Read and write to any database'"
echo ""
echo "4. 🌐 Configure Network Access:"
echo "   - Add IP Address: 0.0.0.0/0 (Allow access from anywhere)"
echo "   - This is needed for Netlify deployment"
echo ""
echo "5. 📋 Get Connection String:"
echo "   - Click 'Connect' → 'Connect your application'"
echo "   - Choose 'Node.js' and version '5.5 or later'"
echo "   - Copy the connection string"
echo "   - It should look like:"
echo "   mongodb+srv://limitbreakers-user:<password>@limitbreakers.xxxxx.mongodb.net/?retryWrites=true&w=majority"
echo ""
echo "6. 🔧 Replace <password> with your actual password"
echo ""
echo "Once you have the connection string, come back and we'll configure the app!"
echo ""
read -p "Press Enter when you've completed the Atlas setup..."
echo ""
echo "✅ Great! Now let's configure your application..."
